# .github/workflows/scrape.yml
name: Scrape council jobs

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write
  actions: read

concurrency:
  group: scraper
  cancel-in-progress: false

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Ensure dirs
        run: |
          mkdir -p data feeds docs/feeds
          touch docs/.nojekyll

      - name: Run scraper
        run: |
          python src/scraper.py \
            --councils data/councils.yaml \
            --out data/jobs_history.jsonl \
            --append \
            --delay 0.3 \
            --log INFO

      - name: Build feeds
        if: ${{ hashFiles('src/feeds_site_builder.py') != '' }}
        run: |
          python src/feeds_site_builder.py \
            --in data/jobs_history.jsonl \
            --out feeds/feed.xml

      - name: Publish feed to /docs for Pages
        run: |
          mkdir -p docs/feeds
          cp -f feeds/feed.xml docs/feeds/feed.xml

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: update feeds/feed.xml for Pages [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
