name: Scrape council jobs

on:
  workflow_dispatch: {}
  schedule:
    # Every 6 hours. CRON is UTC. (Melbourne = UTC+11 on Oct 31, 2025.)
    - cron: "0 */6 * * *"

permissions:
  contents: write
  actions: read

concurrency:
  group: scraper
  cancel-in-progress: false

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Ensure data/ dirs exist
        run: mkdir -p data feeds

      - name: Verify councils registry exists
        run: |
          test -f data/councils.yaml || (echo "data/councils.yaml not found" && exit 1)

      - name: Run scraper (append mode)
        run: |
          python src/scraper.py \
            --councils data/councils.yaml \
            --out data/jobs_history.jsonl \
            --append \
            --delay 0.3 \
            --log INFO

      - name: Show record count
        run: |
          echo "Total rows in jobs_history.jsonl:"
          wc -l data/jobs_history.jsonl || true
          echo "Recent tail:"
          tail -n 5 data/jobs_history.jsonl || true

      - name: Build feeds (optional)
        if: ${{ hashFiles('src/feeds_site_builder.py') != '' && hashFiles('data/jobs_history.jsonl') != '' }}
        run: |
          python src/feeds_site_builder.py \
            --in data/jobs_history.jsonl \
            --out feeds/feed.xml

      - name: Upload artifacts (jobs + feed)
        uses: actions/upload-artifact@v4
        with:
          name: scraper-output
          path: |
            data/jobs_history.jsonl
            feeds/feed.xml
          if-no-files-found: warn
          retention-days: 10

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(scraper): update jobs_history and feed [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
