name: Scrape council jobs

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write
  actions: read
  pages: write            # ← ADD
  id-token: write         # ← ADD

concurrency:
  group: scraper
  cancel-in-progress: false

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    outputs:
      site-path: ${{ steps.site-path.outputs.path }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Ensure data/ dirs exist
        run: |
          mkdir -p data feeds

      - name: Run scraper
        run: |
          python src/scraper.py \
            --councils data/councils.yaml \
            --out data/jobs_history.jsonl \
            --append \
            --delay 0.3 \
            --log INFO

      - name: Build feeds
        run: |
          python src/feeds_site_builder.py \
            --in data/jobs_history.jsonl \
            --out feeds/feed.xml \
            --days 45

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(scraper): update jobs_history and feed [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

      - id: site-path                # ← tell next job where the site files live
        run: echo "path=feeds" >> "$GITHUB_OUTPUT"

  deploy:
    needs: run-scraper
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ needs.run-scraper.outputs.site-path }}  # uploads ./feeds

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
